name: ğŸ“¤ Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      STORE_PATH: ${{ github.workspace }}/.pnpm-store

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: ğŸ”„ Checkout

      - uses: actions/setup-node@v4.0.2
        name: ğŸ› ï¸ Setup Node.js
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3.0.0
        name: âš™ï¸ Setup pnpm
        with:
          version: latest
          run_install: false

      - name: ğŸ“‚ Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: ğŸ—„ï¸ Cache pnpm store
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ—ï¸ Build static content
        run: pnpm build

      - uses: actions/configure-pages@v4.0.0
        name: ğŸ“„ Configure GitHub Pages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          enablement: true

      - uses: actions/upload-pages-artifact@v3
        name: ğŸš€ Upload artifact
        with:
          path: dist

      - uses: actions/deploy-pages@v4.0.4
        id: deployment
        name: ğŸš¢ Deploy to GitHub Pages
